select * from INFORMACION_LABORAL

insert into INFORMACION_LABORAL VALUES (6,'DEPENDIENTE','INGENIERO','2023/02/04', 'TOYOTA', 59422, 1,9, 'BENI', 'SAN BORJA', 'VALLES', 8, 15, 'BIOSEGURIDAD','7')

DELETE FROM INFORMACION_LABORAL

UPDATE INFORMACION_LABORAL 
SET OCUPACION = 'docente';
